package io.brokr.core.model;

public enum AuditActionType {
    CREATE,
    UPDATE,
    DELETE,
    READ,
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    AUTHORIZATION_DENIED,
    AUTHORIZATION_GRANTED,
    CONNECTION_TEST,
    CONFIGURATION_CHANGE,
    BULK_OPERATION,
    EXPORT,
    IMPORT,
    MFA_SETUP_INITIATED,
    MFA_SETUP_COMPLETED,
    MFA_DISABLED,
    MFA_VERIFICATION_SUCCESS,
    MFA_VERIFICATION_FAILED,
    MFA_BACKUP_CODES_REGENERATED
}

